### ISSUE TITLE
Recent 枠調査用にプレー履歴を提供してもらう機能

### ISSUE THREAD

**Issue by zk-phi** [zk-phi/CHUNITHMRateAnalyzer#36]
暇をみてやりたい。
Google のスプレッドシートにデータ受け取るための API を作って、それを叩いて溜めていくのが楽そう。

**Comment by zk-phi** [comment]
クロスドメインの POST で怒られる問題。サーバー側 (Google App Script) 側で JSONP を使うようにするとうまくいくらしい？

http://qiita.com/soundTricker/items/d940ef8db0bd23c0f236

**Comment by zk-phi** [comment]
プレー履歴も chunithm-net の API から取れるので、考察 http://max-eipi.hatenablog.com/entry/2016/08/22/031357 にしたがって Recent 枠を実際に計算してみて、表示レートと矛盾がないか（＝反例がないか）を自動でチェックするのもありかもしれない

ついでに Recent 枠一覧機能も作れそうなので一般のユーザーにも役立ちそう（妄想）

**Comment by zk-phi** [comment]
Recent 枠一覧見れるようにするなら Recent 枠の上がるスコアの下限とかもわかると便利かも

暇ができたらやる

**Comment by MAX-eipi** [comment]
運用していく上で、シートの管理方法をどうするか決めかねています。
現状考慮している管理方法は次の2つです。

### 1. 1ユーザーにつき、1つのシートでプレイ履歴を管理する
- 利点
  - 人間の目でチェックする必要が出てきた時は幾分か楽になるのではないか
  - データの修正をユーザーが直接行うことができる（軽い修正、まとまりをもった修正はシートを直接編集した方が楽な時がある。また、データを修正するためのページを作る必要もなくなる）
- 懸念点
  - そもそもユーザーにシートを所有させる管理形態を採ることができるのか？調査が必要
  - データを改ざんすることができてしまう（最も、それによって悪影響を受けるのは自分自身だが、、）
  - 開発側がユーザーのプレイ履歴を検索することが困難になる（プレイ履歴を提供してもらうのが元々の目的なのだから、それができないと本末転倒）

### 2. 全ユーザーのプレイ履歴を1つのシートで管理する
- 利点
  - 所有者はスクリプト実行権限所有者1人だけで済む
  - シートを直接編集することができないため、データの改ざんはある程度防げる
  - 開発側でデータを検索することが容易である
-  懸念点
  - ユーザーの判別方法は？ユーザーIDで十分？
  - データの修正をするためのページを用意する必要が出てくる
  - 1に比べてデータが肥大化しやすい

自分としては後学のため1が実現可能かどうか調査しつつ、一先ず2の方針で実装を進めて行こうかと考えております。

**Comment by zk-phi** [comment]
データの修正って具体的にどんなことが考えられますか？
自分が想像していたのは、プレー履歴の API にリクエストして、その結果をたとえば

```
ユーザーID (のハッシュ？), 表示レート, 譜面ID, 曲別レート, 譜面ID, 曲別レート, ... (プレー履歴の曲数分繰り返し)
```

みたいな形式で１つのファイルに溜め込んじゃう感じですね。Recent 枠の反例を調査したりするだけなら、解析はこちらでやればいいので、それで十分かなーと思います。

別の案で、 Recent 枠の一覧をユーザーにも見せてもいいかなってのもちょっと考えていて、それをやるならいちいちスプレッドシートにデータを見に行くのも面倒なので、 Best 枠と同じように localStorage  に溜め込んでっちゃうのもアリだと思います（クッキーのめっちゃ強い版みたいなイメージです）。

ユーザー個人のスプレッドシートに溜めていくのは、ユーザーがみんなグーグルのアカウントを持っていないといけないことになるのでちょっと手間かもですね。

**Comment by MAX-eipi** [comment]
先日のコメントですが、自分の中でRecent枠の追跡機能も兼ねることができたらと考えていたため、その機能を考慮して上のようにコメントしたのですが、目的が異なるため(プレイ履歴提供機能の目的はRecent枠遷移の反例チェックで、Recent枠追跡機能の目的はRecent枠、候補枠内訳の把握）、一緒くたにしない方が良いと結論づけました。

(データの修正について、例として、プレイ履歴を送る際、Recent枠を決定する手助けをするために、1プレイごとの表示レートを入力してもらいたいと考えており、それを入力、送信した後で誤りに気付いて修正したくなった、なんてパターンを想定しておりました。)

よって、Recent枠の反例チェックのみを目的にするなら、

> データの修正って具体的にどんなことが考えられますか？
> 自分が想像していたのは、プレー履歴の API にリクエストして、その結果をたとえば
> 
> ユーザーID (のハッシュ？), 表示レート, 譜面ID, 曲別レート, 譜面ID, 曲別レート, ... (プレー履歴の曲数分繰り返し)
> みたいな形式で１つのファイルに溜め込んじゃう感じですね。Recent 枠の反例を調査したりするだけなら、解析はこちらでやればいいので、それで十分かなーと思います。

この方法を軸に実装しようと思います。

なお、カラムの定義は現在検討中ですが、現状は次のようにしたいと考えています。

```
データID(通し番号), ユーザーID, 追加時刻, 表示レート, Best値, 譜面定数, スコア, 譜面定数, スコア, 譜面定数, スコア, ... (プレイ履歴の曲数分繰り返し)
```

・最初の3項目はデータを管理しやすくするために入れてあります。
・表示レートとBest値は逆算Recent値を求めるために必要なデータです。
・1曲分のデータを、(譜面定数, スコア)としていますが、((譜面定数を決定するのに必要なデータ), スコア)となっていれば十分なので、(楽曲ID, 難易度, スコア)とかでも良いですが、現在検討中です。

**Comment by zk-phi** [comment]
いいと思います！ユーザー ID はハッシュしておいたほうがデータを提供してくれるユーザーさんに親切かもですね。
一曲ごとに表示レートを入力させるかは悩みどころですね（取れるレート遷移のデータの精度は上がりますが、提供してくれる人は減ってしまいそうな感じがします）

Recent 枠追跡の機能も必要だなーとは思っているので、そちらの方向で進めていくのもそれで大歓迎ですが、どうしましょう？ｗ

**Comment by MAX-eipi** [comment]
> ユーザー ID はハッシュしておいたほうがデータを提供してくれるユーザーさんに親切かもですね。

なるほどです。どのアルゴリズムを用いれば最適なのかは知識不足ゆえわかりかねますが、ユーザーIDはハッシュするようにします。
<br>

> 一曲ごとに表示レートを入力させるかは悩みどころですね（取れるレート遷移のデータの精度は上がりますが、提供してくれる人は減ってしまいそうな感じがします）

プレイ履歴提供機能のネックな部分が、仰る通り「精度と手間のトレードオフ」になると考えております。
開発側が提供者の負担を軽減するために必要な努力として、"1プレイごとの表示レートを入力してもらわなくても十分実用的である反例チェック方法"を追究することにあると思います。
そのようなチェック方法があれば、この問題は解決するのですが、現状では有効なチェック方法を見いだせてはいません。
チェック方法に関する多くの見解を仰ぐため、フォーラムを設けることも視野に入れています。また、このフォーラムでは"Recent枠を決定するための方法"に関する意見も求めようと考えております。
(そのための具体的な方法は何も考案しておりませんが、、）
自分が現状思いつく案としては以上ですが、他の案が思いつくのであれば是非ご提案頂きたい部分ではあります。
<br>

> Recent 枠追跡の機能も必要だなーとは思っているので、そちらの方向で進めていくのもそれで大歓迎ですが、どうしましょう？ｗ

工数的に見ると、圧倒的にRecent枠追跡機能の実装の方が工数は多くなります。
また、自身の推測が十分保証されていない状態で実装を進めていくのもどうかと思っていることもあり、自分としては大まかに次のような流れにした方が良いのかなとも考えました。
1.プレイ履歴を提供してもらい、遷移推測が十分保証されるまで反例チェックを行う
2.上述したフォーラムで得た意見をまとめ、Recent枠追跡アルゴリズムを構築する
3.構築したアルゴリズムをもとに、Recent枠追跡機能を実装する

ただ、この方法は理想中の理想になると考えております。（反例チェックに期間を要しRecent枠追跡機能の実装開始がなかなか始まらなったり、フォーラムで意見が飛び交うことがそもそもあるかどうかなどの懸念点が挙げられます）

これはあくまで一個人の見解ですので、他の案があれば是非とも共有していただきたいと存じます。

**Comment by zk-phi** [comment]
```

**Comment by zk-phi** [comment]
> 開発側が提供者の負担を軽減するために必要な努力として、"1プレイごとの表示レートを入力してもらわなくても十分実用的である反例チェック方法"を追究することにあると思います。

３曲分のレート推移をシュミレートして、最終結果が合わなければ反例発見、ではまずいですかね？（実は反例だけど最終結果は合ってて検出されないとか、反例見つかったけど具体的にどの曲か一目ではわからない、などの問題はありますが、それで結果データを提供してくれる人が増えるならそちらのほうが美味しい気がします）

**Comment by zk-phi** [comment]
> 1.プレイ履歴を提供してもらい、遷移推測が十分保証されるまで反例チェックを行う
> 2.上述したフォーラムで得た意見をまとめ、Recent枠追跡アルゴリズムを構築する
> 3.構築したアルゴリズムをもとに、Recent枠追跡機能を実装する

β版機能みたいな位置付けで Recent 枠追跡を実装するのもありっちゃありかなーとは思ってます。でもひとまず一番簡単なところからやってもらうので全然いいと思います！
